name: digital_art_gallery
description: A Flutter digital art gallery app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '^3.9.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  image_picker: ^1.1.2
  share_plus: ^12.0.1
  google_fonts: ^6.2.1
  syncfusion_flutter_charts: ^31.2.18

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    # Include the whole images directory so all referenced images are bundled
    - assets/images/
